### ISSUE TITLE
failed to push some refs

### ISSUE THREAD

**Issue by alevinetx** [anishathalye/git-remote-dropbox#108]
This is under cygwin, if that makes any difference

git dropbox version
git-remote-dropbox 2.0.0

- I have selective sync turned off for the repos folders, so they don't appear locally at all

I've tried with several different repo names, just to make sure I wasn't stomping on something strange

The main culprit it looks like:
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

Please let me know what I can do to help you resolve this issue.

 Thank you !

```
 git push --all -v
Pushing to dropbox:///repos/apps/myapp.git
debug: writing: /repos/apps/myapp.git/objects/4a/1faa84a00228ff37f8b4bf35efaf055e92fc9b
debug: writing: /repos/apps/myapp.git/objects/43/324219ad84835fe8170064014f08865681ae87
debug: writing: /repos/apps/myapp.git/objects/c1/62e85418c2cbf69f169204e398e22f1bd8aceb
debug: writing: /repos/apps/myapp.git/objects/66/3feec64c3f0009b510e37a4f648ea6ab2b64da
debug: writing: /repos/apps/myapp.git/objects/d3/a1113cb54899d9e051fde35b7c66dc0bc69efb
debug: writing: /repos/apps/myapp.git/objects/38/839fe3ed37ce88730140d7f80a926e4c4a88b9
debug: writing: /repos/apps/myapp.git/objects/eb/07ad874c14f1bdf22dc102309337f2108b17bf
debug: writing: /repos/apps/myapp.git/objects/ed/1c84101abf50a84317fba8851e8e00a83b4082
debug: writing: /repos/apps/myapp.git/objects/2b/59f23602a2401abfc9221b2eb1d38be1d2f752
debug: writing: /repos/apps/myapp.git/objects/56/c33f33eec06098314c272f70ab7d88fc11e940
debug: writing: /repos/apps/myapp.git/objects/ea/f91e2ac647df635a09f01b8a2a254252aae8d7
debug: writing: /repos/apps/myapp.git/objects/50/3cabfcf60e488300f34c7f232e0af293c7717a
debug: writing: /repos/apps/myapp.git/objects/22/d73eb0d96080922af0bad58225141717f2bd20
debug: writing: /repos/apps/myapp.git/objects/1e/37a059407b727f7d7e58048d06e757e67c8e4e
debug: writing: /repos/apps/myapp.git/objects/be/4c13c15229e646ba32c52841e29d6f19fe91e1
debug: writing: /repos/apps/myapp.git/objects/b8/ff0e48884d7a621115f5265827b019f44989a9
debug: writing: /repos/apps/myapp.git/objects/ab/0e99355337eaa21ebac4a31525f8ad6b29d799
debug: writing: /repos/apps/myapp.git/objects/15/95e0bdc3d5c31c82b367e0a2d9123cc6c52679
debug: writing: /repos/apps/myapp.git/objects/96/61ac713428efbad557d3ba3a62216b5bb7d226
debug: writing: /repos/apps/myapp.git/objects/3b/301b651c22ffa92167037e1f6814d56e100470
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/git-remote-dropbox", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/cli/helper.py", line 23, in main
    helper.run()
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/helper.py", line 108, in run
    self._do_push(line)
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/helper.py", line 152, in _do_push
    self._push(src, dst)
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/helper.py", line 218, in _push
    for done, _ in enumerate(res, 1):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/util.py", line 112, in __call__
    return method(self._obj, *args)
  File "/usr/local/lib/python3.9/site-packages/git_remote_dropbox/helper.py", line 290, in _put_object
    self._connection.files_upload(data, path, mode, mute=True)
  File "/usr/local/lib/python3.9/site-packages/dropbox/base.py", line 3208, in files_upload
    r = self.request(
  File "/usr/local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 304, in request
    self.check_and_refresh_access_token()
  File "/usr/local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 372, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/usr/local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 405, in refresh_access_token
    res = self._session.post(url, data=body, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
error: failed to push some refs to 'dropbox:///repos/apps/myapp.git'
```

**Comment by anishathalye** [comment]
Closing due to age. (Let me know if this is still an issue.)
