### ISSUE TITLE
Failed to push some refs

### ISSUE THREAD

**Issue by faxal** [anishathalye/git-remote-dropbox#15]
I added a remote  with `git remote add dbx "dropbox::/Repos/test"` and when I do `git push dbx`, it gives the following errors:
````
error: unexpected exception
error: failed to push some refs to 'dropbox::/Repos/test'
````

**Comment by anishathalye** [comment]
So… our error reporting isn't very good yet :stuck_out_tongue:
(trying to improve it asap - see #9)

It could be a transient error, or it could be something else.

Could you try running `GIT_TRANSPORT_HELPER_DEBUG=1 git push -vv dbx master` and post the output here?

If you don't want to make the results public, you could anonymize the contents and/or PM stuff to me.

**Comment by faxal** [comment]
Thanks for quick response. Not much to anonymize.

````
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <- 
Debug: Capabilities complete.
Debug: Remote helper: -> option progress true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> option verbosity 3
Debug: Remote helper: Waiting...
Debug: Remote helper: <- ok
Pushing to dropbox::/Repos/test
Debug: Remote helper: Waiting...
Debug: Remote helper: <- 
Debug: Read ref listing.
Debug: Remote helper: -> push refs/heads/master:refs/heads/master

Debug: Remote helper: Waiting...
error: unexpected exception
Debug: Remote helper quit.
error: failed to push some refs to 'dropbox::/Repos/test'
Debug: Disconnecting.
````

**Comment by anishathalye** [comment]
Okay, so this is the most terrible debugging process ever (sorry about that)...

Could you get rid of lines 673-674 so it'll print a stack trace instead of swallowing it? (alternatively, grab [this file](https://gist.github.com/78d4b1ec2eaf3bc7ea8c))

**Comment by faxal** [comment]
It's completely fine. I think this is a  Python-3 string compatibility issue. Changed to Python-2 and it works. 

````
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <- 
Debug: Capabilities complete.
Debug: Remote helper: -> option progress true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> option verbosity 3
Debug: Remote helper: Waiting...
Debug: Remote helper: <- ok
Pushing to dropbox::/Repos/test
Debug: Remote helper: Waiting...
Debug: Remote helper: <- 
Debug: Read ref listing.
Debug: Remote helper: -> push refs/heads/master:refs/heads/master

Debug: Remote helper: Waiting...
Traceback (most recent call last):
  File "/home/fazal/.bin/git-remote-dropbox", line 684, in <module>
    main()
  File "/home/fazal/.bin/git-remote-dropbox", line 672, in main
    helper.run()
  File "/home/fazal/.bin/git-remote-dropbox", line 346, in run
    self._do_push(line)
  File "/home/fazal/.bin/git-remote-dropbox", line 383, in _do_push
    self._push(src, dst)
  File "/home/fazal/.bin/git-remote-dropbox", line 427, in _push
    objects = git_list_objects(src, present)
  File "/home/fazal/.bin/git-remote-dropbox", line 174, in git_list_objects
    return [i.split()[0] for i in objects.split('\n')]
TypeError: 'str' does not support the buffer interface
Debug: Remote helper quit.
error: failed to push some refs to 'dropbox::/Repos/test'
Debug: Disconnecting.
````

**Comment by anishathalye** [comment]
Oh hmm, interesting.

Yeah, when writing the remote helper, I was thinking of trying to maintain Python 2/3 compatibility, but I didn't get around to testing it in v0.

Thanks so much for reporting this issue (and debugging it yourself :smile:). I filed a separate issue on Python 2/3 compatibility, and I'll get around to implementing it soon.

Please let me know if anything else comes up!
