### ISSUE TITLE
Assertion Error on git clone

### ISSUE THREAD

**Issue by faxal** [anishathalye/git-remote-dropbox#17]
I've been getting this stack trace after I push and then try to clone it to a different directory.

````
Traceback (most recent call last):
  File "/home/fazal/.bin/git-remote-dropbox", line 684, in <module>
    main()
  File "/home/fazal/.bin/git-remote-dropbox", line 672, in main
    helper.run()
  File "/home/fazal/.bin/git-remote-dropbox", line 344, in run
    self._do_list(line)
  File "/home/fazal/.bin/git-remote-dropbox", line 369, in _do_list
    refs = self._get_refs(for_push=for_push)
  File "/home/fazal/.bin/git-remote-dropbox", line 621, in _get_refs
    name = self._ref_name_from_path(path)
  File "/home/fazal/.bin/git-remote-dropbox", line 454, in _ref_name_from_path
    assert path.startswith(prefix)
AssertionError
````

**Comment by faxal** [comment]
Did a little digging myself. It seems helper users `path_lower` in `_get_refs` and I was using the path `dropbox::/Repos/test` and it's expecting `dropbox::/repos/test`.

`git clone "dropbox::/repos/test` works.

**Comment by anishathalye** [comment]
Oh, interesting! Yeah, Dropbox is case-insensitive, so I've just been using lower-case URLs.

Okay, opened #18 to take care of this.
