### ISSUE TITLE
error: exception while writing objects

### ISSUE THREAD

**Issue by Drenn1** [anishathalye/git-remote-dropbox#26]
I get this error whenever I try to push something.

```
error: exception while writing objects
error: failed to push some refs to 'dropbox://git/lynnalab'
```

It creates a folder, and even some objects apparently, but it doesn't finish.

I've tried python2, python3, dropbox-sdk v4.0.0, v3.42. Still haven't found a cause. I'm on arch linux.

**Comment by anishathalye** [comment]
Error reporting is still pretty bad atm (still v0.x)...

If you can edit line 438 to no longer suppress the exception (print the full exception info -- you could add a line `import traceback; traceback.print_exc()`) and post it here, I could try to figure out what is wrong.

**Comment by anishathalye** [comment]
(alternatively, I can be more helpful in about 5 days)

**Comment by Drenn1** [comment]
Here's the full exception.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.5/site-packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 783, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f85cbcfcd30>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 608, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f85cbcfcd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/bin/git-remote-dropbox", line 437, in _push
    pool.map(Binder(self, '_put_object'), objects)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/matthew/bin/git-remote-dropbox", line 281, in __call__
    return method(self._obj, *args)
  File "/home/matthew/bin/git-remote-dropbox", line 493, in _put_object
    self._connection().files_upload(data, path, mode, mute=True)
  File "/usr/lib/python3.5/site-packages/dropbox-3.42-py3.5.egg/dropbox/base.py", line 377, in files_upload
    f)
  File "/usr/lib/python3.5/site-packages/dropbox-3.42-py3.5.egg/dropbox/dropbox.py", line 175, in request
    request_binary)
  File "/usr/lib/python3.5/site-packages/dropbox-3.42-py3.5.egg/dropbox/dropbox.py", line 256, in request_json_string_with_retry
    request_binary)
  File "/usr/lib/python3.5/site-packages/dropbox-3.42-py3.5.egg/dropbox/dropbox.py", line 316, in request_json_string
    verify=True,
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f85cbcfcd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
error: exception while writing objects
error: failed to push some refs to 'dropbox://git/lynnalab'
```

That's a lotta exceptions...

**Comment by anishathalye** [comment]
Wow, yeah, that is a lot of exceptions!

It looks like it's a problem with the Dropbox API (with establishing a network connection) and not with git-remote-dropbox.

I know that I've had some issues with repositories with really gigantic files (in the hundreds of megabytes) that were tracked in Git. And I've had some other sporadic issues with the Dropbox API v2 (the Python SDK is still in preview). So I'm not sure what exactly is going on. It's weird that it can't establish a connection at this point, because by the time it's writing objects, it's already used the API to do some reads, so it must have successfully established a connection at least once.

I'm out of the country until Saturday, so it's a little difficult for me to investigate further at the moment, but I can look at stuff in a couple days. In the meantime, let me know if you figure anything out!

(With this Git remote helper, I really have no idea how many users there are, so I can't tell if this is a problem that nobody else is experiencing, or if this is something that nobody has come across yet because not that many people are using this software...)

**Comment by Drenn1** [comment]
Yeah, a lot of people are too shy to report bugs or give up easily, and the dev never knows about it! I used to be like that but then I actually started doing open source projects. Bug tracking's important yo.

This repository doesn't contain anything too huge. It has a submodule with a bunch of binary files but I don't think that would get pushed along with it. Anyway I've tried it with other repositories. Also it hasn't just established a connection, it's created the folders and written a few files too!

Anyway yeah. No rush. This issue's here for whenever you have the time to look at it. :)

**Comment by anishathalye** [comment]
Yeah, thanks for being an active participant in open source!! As a maintainer, I appreciate people who report bugs, and I _really_ appreciate it when people are willing to answer questions about things / actually have a conversation about things.

Wow, that's strange. Yeah, I'll take a look in a couple days.

**Comment by anishathalye** [comment]
I just tried it with the latest version of https://github.com/dropbox/dropbox-sdk-python@9f83c619 and it seems to be working fine for me (Ubuntu 14.04, Python 2.7).

**Comment by jimmyangel** [comment]
I am seeing the same problem on a Mac, running Python 2.7.10 and the latest Dropbox sdk for python.
error: exception while writing objects
error: failed to push some refs to 'dropbox://repo-name'

**Comment by Drenn1** [comment]
Mine is python 2.7.11 / 3.5.1. I'm on arch linux so I initially suspected that bleeding edge packages might be the cause... dunno about that if it's happening on macs too.

**Comment by anishathalye** [comment]
It's working fine on my Mac with Python 2.7.9 and the latest git-remote-dropbox and dropbox-python-sdk.

**Comment by anishathalye** [comment]
I was getting a similar error today for a different reason: https://github.com/dropbox/dropbox-sdk-python/pull/50

**Comment by anishathalye** [comment]
Okay, can't reproduce... :/

If anything similar is still happening, please open another issue.
