### ISSUE TITLE
Pushing repository fails

### ISSUE THREAD

**Issue by rjkyng** [anishathalye/git-remote-dropbox#70]
I'm trying to push a fairly large git repository for the first time. It fails every time I try.

Error message included below.

> rk $ git push -v
Pushing to dropbox:///Repos/research1
debug: writing: /repos/research1/objects/1a/6eda2e816781aa27e8b09ca99553c64cca5846
[... deleted lines ...]
debug: writing: /repos/research1/objects/33/7ea6e0aa8efe47a0b396760871e44f6ba8968a
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/anaconda/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/anaconda/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x11171b860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/anaconda/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11171b860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/bin/git-remote-dropbox", line 11, in <module>
    sys.exit(main())
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 759, in main
    helper.run()
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 372, in run
    self._do_push(line)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 409, in _do_push
    self._push(src, dst)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 461, in _push
    for done, _ in enumerate(res, 1):
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 295, in __call__
    return method(self._obj, *args)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 524, in _put_object
    self._connection().files_upload(data, path, mode, mute=True)
  File "/anaconda/lib/python3.6/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11171b860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
error: failed to push some refs to 'dropbox:///Repos/research1'

**Comment by anishathalye** [comment]
How large is the git repository? Can you give me instructions on how to reproduce this?

I tried two things. I tried a large git repository with lots of small files and many medium-sized files (about 1000 objects total, and 100M total), and it worked for me.

I also tried the following:

```
cd /tmp
mkdir test
cd test
# make a bunch of random large files
dd if=/dev/urandom of=10m.bin bs=1M count=10
dd if=/dev/urandom of=25m.bin bs=1M count=25
dd if=/dev/urandom of=50m.bin bs=1M count=50
dd if=/dev/urandom of=100m.bin bs=1M count=100
git init
git add .
git commit -m 'bla'
git push dropbox:///test master:master
```

This also worked just fine for me.

**Comment by anishathalye** [comment]
Any updates?

**Comment by rjkyng** [comment]
Hi,

Your code also worked for me, but going for slightly larger files caused problems.

The following produced an error for me:

```
mkdir test2
cd test2

dd if=/dev/urandom of=10m.bin bs=1m count=10
dd if=/dev/urandom of=25m.bin bs=1m count=25
dd if=/dev/urandom of=50m.bin bs=1m count=50
dd if=/dev/urandom of=100m.bin bs=1m count=200

git init
git add .
git commit -m 'bla'
git push -v dropbox:///repos/test2 master:master
```

Output was 
```
git push -v dropbox:///repos/test2 master:master
Pushing to dropbox:///repos/test2
debug: writing: /repos/test2/objects/5f/8e4b42782f7371960f07221309852cc73ab3c9
debug: writing: /repos/test2/objects/df/d3a33b02c59fbaa8a58737cfe3e34cab2f0d76
debug: writing: /repos/test2/objects/5e/462ee0e672e3db01856ce741d8948237894328
debug: writing: /repos/test2/objects/f9/3e93168fe093e67561873e0037bc50ac242e42
debug: writing: /repos/test2/objects/6d/98c751aa01c10121d73025a754739229ff33e0
debug: writing: /repos/test2/objects/c8/9dabfd26f91ed832b8457bcd8e1c81ebca3a12

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/anaconda/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/anaconda/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/anaconda/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/anaconda/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/anaconda/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/anaconda/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/bin/git-remote-dropbox", line 11, in <module>
    sys.exit(main())
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 759, in main
    helper.run()
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 372, in run
    self._do_push(line)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 409, in _do_push
    self._push(src, dst)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 461, in _push
    for done, _ in enumerate(res, 1):
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
  File "/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 295, in __call__
    return method(self._obj, *args)
  File "/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 524, in _put_object
    self._connection().files_upload(data, path, mode, mute=True)
  File "/anaconda/lib/python3.6/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Read timed out. (read timeout=30)
error: failed to push some refs to 'dropbox:///repos/test2'
```

**Comment by anishathalye** [comment]
Huh. Well, I don't think we can do anything about this -- this isn't a bug in git-remote-dropbox, I think it's an issue with the Dropbox API. I'm not sure we can work around it without complicating our on-disk format (by e.g. splitting up large files).

**Comment by IcePhoenX** [comment]
The [doc](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload) clearly states that ``files_upload`` should not be used with files greater than 150MB and instead use an upload session with ``files_upload_session_start``.
I'll be happy to implement it, when I have the time.

**Comment by anishathalye** [comment]
Oh haha that's a good catch!

Sure, it'll be great to have this feature. (Though I guess it isn't super critical since most people probably won't have > 150MB files in their repo)

**Comment by johntrimble** [comment]
I've created PR #75 which I believe addresses this issue.
