### ISSUE TITLE
Token Scope Error

### ISSUE THREAD

**Issue by hassan-shehawy** [anishathalye/git-remote-dropbox#99]
Hi, I followed the steps to use your tool. However, I got the following error wen I tried to push: 

(not sure if it's relevant, but I've double checked the token is correct and the options of files.metadata.write, files.metadata.read
files.content.write and files.content.read in the Files and folders section in the Permissions tab are checked in the Dropbox App)

`Pushing to dropbox:///home/hassan/Dropbox (ORGN)/test`
`Traceback (most recent call last):`
  `File "/home/hassan/.local/bin/git-remote-dropbox", line 8, in <module>
    sys.exit(main())`
  `File "/home/hassan/.local/lib/python3.6/site-packages/git_remote_dropbox/cli/helper.py", line 23, in main
    helper.run()`
  `File "/home/hassan/.local/lib/python3.6/site-packages/git_remote_dropbox/helper.py", line 106, in run
    self._do_list(line)`
  `File "/home/hassan/.local/lib/python3.6/site-packages/git_remote_dropbox/helper.py", line 131, in _do_list
    refs = self.get_refs(for_push=for_push)`
  `File "/home/hassan/.local/lib/python3.6/site-packages/git_remote_dropbox/helper.py", line 466, in get_refs
    res = self._connection().files_list_folder(loc, recursive=True)`
  `File "/home/hassan/.local/lib/python3.6/site-packages/dropbox/base.py", line 1956, in files_list_folder
    None,`
  `File "/home/hassan/.local/lib/python3.6/site-packages/dropbox/dropbox_client.py", line 327, in request
    timeout=timeout)`
  `File "/home/hassan/.local/lib/python3.6/site-packages/dropbox/dropbox_client.py", line 482, in request_json_string_with_retry
    timeout=timeout)`
  `File "/home/hassan/.local/lib/python3.6/site-packages/dropbox/dropbox_client.py", line 607, in request_json_string
    raise AuthError(request_id, err)`
`dropbox.exceptions.AuthError: AuthError('16110c84b0a543a5bc08cd88b8927672', AuthError('missing_scope', TokenScopeError(required_scope='files.metadata.read')))`

**Comment by anishathalye** [comment]
Thanks for the update, and glad you got it working.

I'm slightly confused -- so are the instructions in the README incorrect? (Do steps 7 and 8 need to be switched?)

**Comment by hassan-shehawy** [comment]
Yes indeed, switching steps 7 and 8 was the correct method.

Thanks

**Comment by anishathalye** [comment]
Thanks! Updated instructions in 3a629487a6c0af0d83a6dd01aa70cb357e4b3b81.
